### PR TITLE
Fix rv32ec/cswsp test generation

### PR DESCRIPTION
**Pull request by bilalsakhawat-10xe**
Fix for the issue [206](https://github.com/riscv-non-isa/riscv-arch-test/issues/206)

### CODE REVIEW

**Comment by neelgala** [comment]
@bilalsakhawat-10xe thanks.. need an entry in changelog.md and a patch [bumpversion](https://github.com/riscv-software-src/riscv-ctg/blob/master/CONTRIBUTING.rst#deploying)

**Comment by bilalsakhawat-10xe** [comment]
@neelgala done.

**Comment by neelgala** [comment]
oops.. you were a little late.. you will need to rebase and make the version 0.5.7 everywhere.. sorry about that.

**Comment by bilalsakhawat-10xe** [comment]
@neelgala done. I also made a [pull request](https://github.com/riscv-non-isa/riscv-arch-test/pull/210) in riscv-arch-test

**Pull request merged**
