### PR TITLE
Add support for Zfinx and Zfh extension

### PR DESCRIPTION
**Pull request by anuani21**
**Added Support for Zfh and Zfinx extensions**

This PR adds

- Added cover group format  for RV32Zfh instructions.
- Added cover group format for RV64Zfh instructions.
- Added cover group format for RV64Zfinx  instructions.
- Introduced half width and half word in Nan boxing functionality to accommodate Zfh extensions.
- Introduced two new flags (ZFINX and ZDINX) to aid the compilation of floating ops into integer regs.

### CODE REVIEW

**Comment by anuani21** [comment]
@neelgala , -Please have your review and let us know if more information would help.

**Comment by anuani21** [comment]
@neelgala , -Please have your review and let us know if more information would help.

**Comment by anuani21** [comment]
@allenjbaum,Can you please review this PR for approval?

**Comment by allenjbaum** [comment]
I'm not familiar enough with CTG to do a good job of reviewing this (though more comments would help a lot. If you've run this under riscof, and it passes tests with the correct coverage, for RV64 and RV32, with & without D/Dinx  configuration, then that's the major thing. Defining coverage is what I want to see, and these extensions have more corner cases to watch out for, especially register assignments, nan-Boxing, etc.

**Comment by allenjbaum** [comment]
Hmm - I'm not sure we should still be referring to incoresemi license details for any of tese; that somehow seems wrong (As opposed to the icense terms that most other repos use)

**Comment by wychlw** [comment]
After some digging, seems some of the ctg files need changes on `check ISA`, like in `rv32h_fdiv.cgf#L5`
```
      - check ISA:=regex(.*I.*F.*)
```
Should be 
```
      - check ISA:=regex(.*I.*F.*Zfh.*)
```

The related issues are: 
https://github.com/riscv-non-isa/riscv-arch-test/issues/453
https://github.com/riscv-non-isa/riscv-arch-test/issues/448

Maybe some changes are needed?

**Comment by UmerShahidengr** [comment]
@anuani21, I have made a commit to resolve the conflicts and to enable the CI. It seems like CI is failing, please take a look at it.

**Comment by anuani21** [comment]
Ok, I will check and let you know

**Comment by anuani21** [comment]
@UmerShahidengr, Can you please review it and commit

**Comment by UmerShahidengr** [comment]
@anuani21 CI is still failing. I think there is some issue in test generation for rv32 type tests.

**Comment by anuani21** [comment]
@UmerShahidengr, Can you please review it and commit??

**Review by UmerShahidengr — APPROVED** [review]
Looks good to go

**Pull request merged**
