### PR TITLE
Fixing Address Offset for F&D Instructions

### PR DESCRIPTION
**Pull request by ptprasanna**
Hi,
This merge request had the below changes on CTG towards Floating point fixes. And the code changes are verified against below, on all of the given instructions across cover groups.

    RV64F
    RV32D
    RV32F
    RV64D

High level descriptions of changes made
_generator.py_
1. Added a condition to manipulate the offset with respect to FLEN
2. Addition of new instructions to the required conditions

_template.yaml_
1. Removal of additional FLEN value from the respective instructions block

Thanks
Prasanna T
ptprasanna@gmail.com

### CODE REVIEW

**Review by allenjbaum — COMMENTED** [review]
This isn't making sense to me; 
flen xlen offset
8B   4B     8 
4B    4B    8
8B    8B   16 
4B    8B   12 
IF this is supposed to maintain alignment after storing 1 Flen reg and one Xlen reg, then the offsets must be 16, 8, 16, 16,  not 8,8,16,12     else the result is left unaligned. 
Am I misunderstanding what this is doing?

**Comment by pawks** [comment]
The test to check whether the instruction is a fp instruction is performed by checking if the first letter of the instruction is `f` whereas this check should be based on the `isa` field in the nodes of the `template.yaml`. This also needs to be fixed.

**Comment by ptprasanna** [comment]
@pawks Not only those, there are many other issues/improvements that we have to address. But those are not in the scope of this PR. This PR only addresses the changes made, nothing more. Probably we may have to address those other improvements and issues as part of separate task.

**Review by allenjbaum — APPROVED** [review]
This looks correct under the assumption that this is for the case that both an Freg and an Xreg are being stored (which is when SIGUPD_F is begin used, but not SIGUPD_FID)

**Comment by pawks** [comment]
> This looks correct under the assumption that this is for the case that both an Freg and an Xreg are being stored (which is when SIGUPD_F is begin used, but not SIGUPD_FID)

I was actually wondering whether it makes sense to do a `flw` followed by a `fsd` for all the `F` instructions in a `D` configuration. What this allows us to ensure is that NaN boxing is correctly performed for the relevant operations. However, doing it for all the operations for every single test case might look like an overkill. There are only 2 possible coverpoints of interest IMO. One with a + result and another with a negative result so that we can ensure that the writes to the registers are not zero/sign extended and always NaN boxed. But the quality is higher if we do it for all the test cases.

**Comment by allenjbaum** [comment]
The cost of leaving it way it is is merely the size of the signature. 
The cost of changing it is the work to figure out which tests should leave it the way it is, and which should change it.
That sounds like the cost of "optimizing" it outweighs the cost of just elaving it.

**Pull request merged**
