### PR TITLE
updates to cgf, added method for generating patterns specific for bitmanip

### PR DESCRIPTION
**Pull request by anku-anand**
Updated decimal values in cgf to hexa for bitmanip instructions.
Added a method for generating patterns like 0x3,0xc 0x9, 0x6 0xa,0x5

### CODE REVIEW

**Review by allenjbaum — CHANGES_REQUESTED** [review]
The commit message has patterns 3333,5555,6666,9999,aaaa,cccc,0,1 - not sure why 0x0001 is significant, but 0xffff isn't, yet the dataset definition does include it but not 0x0001
also, the dataset definition seems inconsistent, as it has both the above values and 0xffff, as well as 0x0003 and 0x0005.  
The rol operation definition template appears to be a shift left, not a rotate left
The long constants in rev8 really need to be hex numbers, not decimal, e.g.0x01020408,  or 0801020408010204. I'm not sure why 64 and 32 bit numbers are mixed in the same dataset, but that doesn't mean its a bug. 
At best it is redundant, and you should make the top and bottom halves different (e.g.    0x08010204 F8F1F2F4 or something to get increased coverage.

**Review by allenjbaum — DISMISSED** [review]
Not quite sure why you kept dataset0 separate like that, but it wprks

**Comment by pawks** [comment]
Changelog and bumpversion updates are missing.

**Comment by anku-anand** [comment]
Hi,

Updated the changelog and version strings.

Thanks & Regards,
Anand

**Review by pawks — APPROVED** [review]

**Pull request merged**
